version: '2'
services:
  db:
    volumes:
       - "itf_data:/var/lib/mysql"
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
volumes:
    itf_data: